version: '3.8'

services:
  backend:
    build: 
      context: ./LotusIslandBackend
      dockerfile: Dockerfile
    ports:
      - "5000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase

  frontend:
    build: 
      context: ./LoutesIsland_Admin_FrontEnd
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
