apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: mern-app  
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2  
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: {{DOCKER_IMAGE_BACKEND}}  
        ports:
        - containerPort: 3000  
        env:
        - name: MONGO_URI
          value: mongodb+srv://kavishkajaye:WZhZIJg8mQlqZxRY@lotusislandtours.ruxct.mongodb.net/?retryWrites=true&w=majority&appName=LotusIslandTours

        - name: NODE_ENV
          value: production
        # Add any additional environment variables your app needs
