---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: mern-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: {{DOCKER_IMAGE_FRONTEND}}  # Replace this or let CI handle
          ports:
            - containerPort: 4000
          env:
            - name: REACT_APP_API_URL
              value: http://backend:3000/api  # Internal service URL

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: mern-app
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - port: 80
      targetPort: 4000
      nodePort: 30080
