apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: mern-app
spec:
  selector:
    app: backend
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: mern-app
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 4000
    nodePort: 30080 
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mern-app
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
